name: Build (Maven)

# Trigger workflow on every push and PR
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your code
      - uses: actions/checkout@v4

      # 2. Install Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      # 3. Build with Maven
      - name: Build with Maven
        run: mvn -B -q -e -DskipTests package

      # 4. Run smoke test (your CLI "list" command)
      - name: Run CLI (smoke test)
        run: mvn -q -Dexec.mainClass=com.example.pensions.App -Dexec.args='list' exec:java | head -n 20
